### ISSUE TITLE
Breaking changes not working

### ISSUE THREAD

**Issue by hugobloem** [ytanikin/pr-conventional-commits#22]
Hi, thank you for developing this action. It is quite useful in verifying the PR titles.

However, it seems that titles with breaking changes using an `!` are not parsed correctly. I am aware of the previous issues #2, #8, and #11 but unfortunately the issue still persists.

Version: 1.2.0
PR title: refactor(load)!: rename load_folder to load_deployment_folder #198

Thank you,
Hugo

**Comment by alexangas** [comment]
After some digging, I found this is inherited behaviour from the conventional-commits-parser. In fact it has an almost identical issue which fortunately contains the fix: https://github.com/conventional-changelog/conventional-changelog/issues/648#issuecomment-704867077. I have a PR here to apply the fix to this GitHub action.
